# Generated by Django 2.1.7 on 2019-02-16 21:31

from django.db import migrations, models
import game.internal_types


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190216_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[(game.internal_types.GameType('bot'), 'bot'), (game.internal_types.GameType('multiplayer'), 'multiplayer')], max_length=30),
        ),
    ]
