# Generated by Django 2.1.7 on 2019-02-16 21:37

from django.db import migrations
import enumchoicefield.fields
import game.types


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190216_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='type',
            field=enumchoicefield.fields.EnumChoiceField(enum_class=game.types.GameType, max_length=11),
        ),
    ]
