# Generated by Django 2.1.7 on 2019-04-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190409_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='captures_o',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='captures_x',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
